version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
     working_directory: ~/bujordet
     steps:
      - checkout
       - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
       - run: yarn install
       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
       - run: yarn test
